apiVersion: v1
kind: Namespace
metadata:
  name: testing

---
##### Hostname #####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment
  namespace: testing
  labels:
    app: hostname-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostname-app
  template:
    metadata:
      labels:
        app: hostname-app
    spec:
      containers:
        - name: hostname-container
          imagePullPolicy: IfNotPresent
          image: hostname:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hostname
  namespace: testing
  labels:
    app: hostname-service
spec:
  selector:
    app: hostname-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
---

##### Nginx #####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: testing
  labels:
    app: nginx-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-container
          imagePullPolicy: IfNotPresent
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: testing
  labels:
    app: nginx-service
spec:
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 80
---

##### Sleep #####
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep-deployment
  namespace: testing
  labels:
    app: sleep-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sleep-app
  template:
    metadata:
      labels:
        app: sleep-app
    spec:
      containers:
        - name: sleep-container
          imagePullPolicy: IfNotPresent
          image: sleep:latest
          ports:
            - containerPort: 80
---
