apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  namespace: bookinfo
  name: details
spec:
  host: details
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
      trafficPolicy:
        outlierDetection:
          consecutiveErrors: 2
          interval: 1m
          baseEjectionTime: 5m
          maxEjectionPercent: 100
