apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bookinfo
  name: details-v2
  labels:
    app: details
    version: v2
spec:
  replicas: 4
  selector:
    matchLabels:
      app: details
      version: v2
  template:
    metadata:
      labels:
        app: details
        version: v2
    spec:
      serviceAccountName: bookinfo-details
      containers:
        - name: details
          image: sixeyed/examples-bookinfo-details-v2:1.18.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
          env:
            - name: SERVICE_VERSION
              value: v-50-50-unhealthy
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  namespace: bookinfo
  name: details
spec:
  host: details
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: bookinfo
  name: details
spec:
  hosts:
    - details
  http:
    - route:
        - destination:
            host: details
            subset: v2
