apiVersion: v1
kind: Namespace
metadata:
  name: demo1
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: demo1
  labels:
    app: todolist
    service: todolist
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: todolist
  # type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: demo1
  name: todolist
  labels:
    account: todolist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  namespace: demo1
  labels:
    app: todolist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      serviceAccountName: todolist
      containers:
      - name: todolist
        image: todo-list-app:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  namespace: demo1
  name: todolist-gateway
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: demo1
  name: todolist
spec:
  hosts:
  - "*"
  gateways:
  - todolist-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: todolist
        port:
          number: 3000