# apiVersion: v1
# kind: Namespace
# metadata:
#   name: hostname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-deployment
  # namespace: hostname
  labels:
    app: hostname-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostname-app
  template:
    metadata:
      labels:
        app: hostname-app
    spec:
      containers:
        - name: hostname-container
          imagePullPolicy: IfNotPresent
          image: morufajibikehub/hostname:v0.0.1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hostname-service
  # namespace: hostname
  labels:
    app: hostname-service
spec:
  selector:
    app: hostname-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80