### We need to install VerticalPodAutoscaler first ###
## git clone https://github.com/kubernetes/autoscaler.git
## cd autocaler
## ./vertical-pod-autoscaler/hack/vpa-up.sh 

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: utility-api
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: utility-api
  updatePolicy:
    updateMode: "Off"