apiVersion: v1
kind: Service
metadata:
  name: numbers-web
  namespace: rng
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: rngsixeyedcom
  labels:
    app: numbers-web
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: numbers-web
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: numbers-web
  namespace: rng
  labels:
    account: numbers-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbers-web
  namespace: rng
  labels:
    app: numbers-web
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: numbers-web
      version: v1
  template:
    metadata:
      labels:
        app: numbers-web
        version: v1
    spec:
      serviceAccountName: numbers-web
      containers:
      - image: kiamol/ch03-numbers-web
        name: numbers-web
        resources:
          limits:
            cpu: 250m
            memory: 200Mi
        ports:
        - containerPort: 80
          name: http
        env:
          - name: RngApi__Url
            value: http://numbers-api.rng/rng