apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bookinfo
  name: productpage-v2
  labels:
    app: productpage
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productpage
      version: v2
  template:
    metadata:
      labels:
        app: productpage
        version: v2
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
        - name: app
          image: sixeyed/examples-bookinfo-productpage-v2:1.18.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  namespace: bookinfo
  name: productpage
spec:
  host: productpage
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  namespace: bookinfo
  name: bookinfo
spec:
  hosts:
  - bookinfo.local
  gateways:
  - istio-ingress/gateway
  exportTo:
  - istio-ingress
  http:
  - route:
    - destination:
        host: productpage
        subset: v1
        port:
          number: 9080
      weight: 70
    - destination:
        host: productpage
        subset: v2
        port:
          number: 9080
      weight: 30
