apiVersion: apps/v1
kind: Deployment
metadata:
  name: numbers-api
  namespace: rng
  labels:
    app: numbers-api
    version: v1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: numbers-api
      version: v1
  template:
    metadata:
      labels:
        app: numbers-api
        version: v1
        sidecar.istio.io/inject: 'true'
    spec:
      serviceAccountName: numbers-api
      containers:
      - image: kiamol/ch03-numbers-api
        name: numbers-api
        resources:
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 80
          name: http