
name: Deploy to EKS

on:
  push:
    branches: [master, cicd-setup]
  pull_request:
    branches: [master]

env:
  DOCKER_USERNAME: morufajibikehub
  DOCKER_IMAGE_REPO: hostname
  DOCKER_IMAGE_DOCKERFILE_FOLDER: sample-apps/hostname

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 

    #   # add a step to get the current image tag
    #   - name: Get current image tag
    #     run: |
    #       IMAGE_TAG=$(grep 'image: ' argocd-cicd-setup/kubernetes/manifest.yaml | awk -F ':' '{print $3}')
    #       echo "Current image tag: $IMAGE_TAG"
    #       echo "::set-env name=IMAGE_TAG::$IMAGE_TAG"

      # Build Docker image and push it to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ${DOCKER_USERNAME}/${{ env.DOCKER_IMAGE_REPO }}:latest -f ${{ env.DOCKER_IMAGE_DOCKERFILE_FOLDER }}/Dockerfile ${{ env.DOCKER_IMAGE_DOCKERFILE_FOLDER }}
          docker push ${DOCKER_USERNAME}/${{ env.DOCKER_IMAGE_REPO }}:latest

    # # add a step to update the image in the Kubernetes manifest file
    #   - name: Update Kubernetes manifest file
    #     run: |
    #       sed -i 's|image: .*$|image: ${DOCKER_USERNAME}/${{ env.DOCKER_IMAGE_REPO }}:latest|' argocd-cicd-setup/kubernetes/manifest.yaml

    # # add another step to commit and push the changes to the repository
    #   - name: Commit and push changes
    #     run: |
    #       git config --global user.email "auto-commit@github.com"
    #       git config --global user.name "GitHub Actions"
    #       git add argocd-cicd-setup/kubernetes/manifest.yaml
    #       git commit -m "Update image in Kubernetes manifest file"
    #       git push
    